### PR TITLE
New Design Updates

### PR DESCRIPTION
**Pull request by Pineapple-1**
This pull request introduces the latest design updates across relevant components. The following changes were made to align with the new design specifications:

Updated styling and layout based on the provided design files.
Adjusted  structures to accommodate new  assets.

Refined responsive behavior for improved consistency across screen sizes.

### CODE REVIEW

**Comment by amark** [comment]
yaaaay glad this is rolling.

Delighted to see nice CSS naming and clean simple HTML! Thank you, great job.

Quite a few cleanup pieces tho, apologies:

Screen Shot 2024-10-29 at 10 18 14 AM
Screen Shot 2024-10-29 at 10 18 17 AM
- [ ] switch back to using the original home/skyline file: it was significantly brighter, higher quality, zoomed out.
- [ ] use CSS `border-radius: 1em 1em 0 0` to add card curve to the top image, NOT curve it in the file itself (applies to all future similar things as well).
- [ ] Upper left Checkard logo please switch back to the original html/css or size / placement / color / font & image.
- [x] (A) I was hoping the text glow effect was going to export as a CSS trick rather than SVG so it could be applied to other headers later. My assumption is Figma does not support that option? Use the SVG in this PR for now tho in future maybe want us to replicate it in CSS. (B) Similar about the $99 text, but let's leave it for now and just use the SVG. (C) The `GET ACCESS` box does do the effect in CSS and is not SVG (yaaaay!!!), however it seems like its done with 5 layer combo which I do prefer over SVG however I'm pretty sure this can be done with `box-shadow` (+ maybe a `outline` and/or `filter` like you have) since box-shadow allows you to have multiple shadows (so you could do all them in 1 property) without multiple HTML elements (or using a ::before ::after). Anyways, ignore this for now, CSS > HTML > SVG. But I'd rather get the SVG shipped than worry about this, more important things to do.
- [ ] I know we don't have URLs yet, but all the clickable items (buttons, footer links, etc.) need to be actual links, I'll add the URLs but I don't myself to do the work of converting them to link `a` tags because browsers do weird default styling modifications that I'll leave to you to correct/perfect. So please make everything clickable be actual links in the HTML so its simple for me to add the URLs and I'll also add the `form` action/js code as well.
- [ ] can we please keep the check tick as a regular ASCII check tick not an SVG, I'm sure one of the current fonts we have loaded has a nice ASCII check tick in it already. 

Sorry, please reverse most of the organization:
1. `/+/` is our asset/etc. folder, so `hi.html` file should remain in and as `/+/hi.html`
2. sure fonts can have their own sub folder but INSIDE `/+/fonts/*` not `/fonts/*`
3. Use original cityhome (it was MUCH higher quality, only 0.5MB with jpg vs the new one is 3MB+  and low quality cause PNG), likewise re-export the new city photo as 0.5MB jpg as just `/+/office.jpg` don't delete the old one.
4. I probably rather the other SVG/icons just still be in `/+/*` but if important to you (7/10+) you can drop them into `/+/icons/*`

Thanks! I think thats all for now.

**Comment by Pineapple-1** [comment]
All requested updates are done except for a CSS-based text glow. This will take time and resources to perfect without SVGs, but I can do it if needed.

Let me know if anything else is needed before merging! 😃 😃

**Comment by amark** [comment]
I'm filling in links and making some minor change, but I'm busy traveling so may be few days.

Still add the new office photo tho (please export as ~0.5MB office.jpg) so I have both in folder I still want to use the new office one (just didn't want the old one deleted).

Thank you!

**Comment by amark** [comment]
... phone got stolen in Panama, laptop overheated, then Tahoe & Thanksgiving happened, remembered I had to build a "push" notification system for GUN so I get tagged if I don't have any of my apps open, and then actually clean/polish/tidy things up + my avoidant nature of not liking laptops anymore, but end of month hit and I need to send an update out so... here we go let's see if this looks pretty in prod!!! Thanks for getting this ready for me, sorry I was a bottleneck.

**Pull request merged**
