### PR TITLE
show both sides of check for printing a paper copy

### PR DESCRIPTION
**Pull request by jazzyjackson**

### CODE REVIEW

**Comment by amark** [comment]
loving the use of the module system, BTW, for everything, from just CSS additions to JS to HTML ui. It's so great to just see a little load statement tossed into bottom of index. Feels so nice and extensible, flexible, progressively enhanced, self-contained, yum!

**Comment by jazzyjackson** [comment]
oh you were right, committed while I was still debugging by just applying the css globally. scoped to just print dialog now and renamed, ready to go.

**Comment by amark** [comment]
Looks good, merging what have so far, BUT two problems:

1) my center-center allow-zoom CSS fix now causes the front side to be middle of page, and backside to be below that which bleeds past printed page margin. So maybe toss in a -margin (?)

2) the printed page still has the check as blue... should we make it white to not mess up someone's printer color?

resolve both those please!

**Comment by jazzyjackson** [comment]
Can you screenshot ? i'm unable to reproduce, production site looks good to me.

**Comment by jazzyjackson** [comment]
nevermind I'm seeing it now, an empty check prints fine but a filled check has a bunch of margin, intriguing.

**Pull request merged**
